version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/valet-sh/valet-sh-installer/cmd.version={{.Version}}

archives:
  - formats: [ 'binary' ]
  - name_template: >-
      valet-sh-{{ .ProjectName }}_
      {{- if eq .Os "darwin" }}darwin
      {{- else if eq .Os "linux" }}linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
